### ISSUE TITLE
Why cLR-GAN cause a 15% same results?

### ISSUE THREAD

**Issue by xml94** [junyanz/BicycleGAN#70]
Thanks for your reamarkable work first and your paper. It seems I learned a lot from your paper.

I am thinking about why cLR-GAN cause same results mentioned in your paper.
And by the way, do your results show that cVAE-GAN don't have similar result because your paper does talk about it.

According to my knowledge, cLR-GAN should have better variation but poor image fidelity in that this method has no L1 loss in target domain B. In this way, the generator in cLR-GAN would explore better in latent space and therefore it has better diversity. Becase of no L1 loss, output tend to have artifacts metntioned in pix2pix paper.

Thanks in advance.

**Comment by junyanz** [comment]
Pixel reconstruction loss will not necessarily cause artifacts. Pixel reconstruction loss will force the encoder to extract useful information from the image and the generator to use such information. This can sometimes increase the diversity of the results.  Otherwise, the generator can choose to ignore the latent code.

**Comment by xml94** [comment]
Thanks for your reply.
I realized that I misunderstanded the impact of pixel reconstruction loss.
I am going to see pix2pix paper to find out the influence.

It seems that you wanted to use 'decrease' instead of 'increase'  about the diversity in your anwser?
