### ISSUE TITLE
Distribution of latent code Z

### ISSUE THREAD

**Issue by viethungtsdv** [junyanz/BicycleGAN#74]
Dear @junyanz ,

Thank you very much for great paper. I have question related to distribution of latent code Z. In your code use a normal distribution (torch.randn(batch_size, nz). What happen if I use other distribution (ex: MultivariateNormal of pytorch)?

**Comment by junyanz** [comment]
You are free to try. It might make the computation of KL divergence slightly more involved. We follow the original [VAE](https://arxiv.org/pdf/1312.6114.pdf) paper and use a multivariate normal distribution with `nz` dimension and diagonal covariance matrix.

**Comment by Rekkouza** [comment]
Dear @junyanz ,
I have read your paper and it seems very interesting for the work I have to do.
What interests me in particular is the use of the latent code and its injection to the generator.
I would like to know if it was possible to inject a scalar value (from a curve for example) instead of a distribution.

**Comment by junyanz** [comment]
It is possible. You can treat it as a 1-dimensional vector. You probably need to remove the KL loss.
